# Generated by Django 6.0.1 on 2026-02-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'raw_news',
                'indexes': [models.Index(fields=['scraped_at', 'is_processed'], name='raw_news_scraped_103ded_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_bn', models.CharField(max_length=500)),
                ('bullet_points', models.JSONField()),
                ('bullet_points_bn', models.JSONField()),
                ('exam_focus', models.TextField()),
                ('exam_focus_bn', models.TextField()),
                ('category', models.CharField(choices=[('national', 'National'), ('international', 'International'), ('economy', 'Economy'), ('sports', 'Sports'), ('science', 'Science & Technology'), ('government', 'Government Orders'), ('awards', 'Awards & Appointments'), ('important_days', 'Important Days')], max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('exam_relevance', models.JSONField(default=list)),
                ('publish_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('bookmark_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed', to='news.rawnews')),
            ],
            options={
                'db_table': 'processed_news',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNewsInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.processednews')),
            ],
            options={
                'db_table': 'user_news_interactions',
            },
        ),
    ]
