# Generated by Django 6.0.1 on 2026-02-03 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usernewsinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='processednews',
            index=models.Index(fields=['category', 'publish_date'], name='processed_n_categor_a5274e_idx'),
        ),
        migrations.AddIndex(
            model_name='processednews',
            index=models.Index(fields=['is_active', 'is_premium'], name='processed_n_is_acti_8dc74c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernewsinteraction',
            unique_together={('user', 'news')},
        ),
    ]
