# Generated by Django 6.0.1 on 2026-02-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=300)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='ebooks/')),
                ('cover_image', models.ImageField(upload_to='ebook_covers/')),
                ('page_count', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monthly_ebooks',
                'unique_together': {('month', 'year')},
            },
        ),
    ]
